# Generated by Django 4.2.2 on 2024-11-23 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_doctor_avatar'),
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.PositiveIntegerField(default=0, verbose_name='сумма к оплате')),
                ('analyses', models.ManyToManyField(related_name='carts_analyses', to='services.analysis', verbose_name='анализы')),
                ('appointments', models.ManyToManyField(related_name='carts_appointments', to='services.appointment', verbose_name='записи на прием')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'козина',
                'verbose_name_plural': 'корзины',
            },
        ),
    ]
