# Generated by Django 4.2.2 on 2024-11-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_doctor_avatar'),
        ('users', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyses', models.ManyToManyField(related_name='histories_analyses', to='services.analysis', verbose_name='анализы')),
                ('appointments', models.ManyToManyField(related_name='histories_appointments', to='services.appointment', verbose_name='записи на прием')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('results', models.ManyToManyField(related_name='histories_results', to='services.result', verbose_name='результаты')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
            },
        ),
    ]
