# Generated by Django 4.2.2 on 2024-12-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_appointment_options_and_more'),
        ('users', '0004_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='history',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='history',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='history',
            name='results',
        ),
        migrations.AddField(
            model_name='cart',
            name='analyses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_analyses', to='services.analysis', verbose_name='анализ'),
        ),
        migrations.AddField(
            model_name='cart',
            name='appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_appointments', to='services.appointment', verbose_name='прием'),
        ),
        migrations.AddField(
            model_name='history',
            name='analyses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_analyses', to='services.analysis', verbose_name='анализ'),
        ),
        migrations.AddField(
            model_name='history',
            name='appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_appointments', to='services.appointment', verbose_name='прием'),
        ),
        migrations.AddField(
            model_name='history',
            name='results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_results', to='services.result', verbose_name='результат'),
        ),
    ]
