# Generated by Django 4.2.2 on 2024-12-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_appointment_options_and_more'),
        ('users', '0005_remove_cart_analyses_remove_cart_appointments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='summ',
        ),
        migrations.RemoveField(
            model_name='history',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='history',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='history',
            name='results',
        ),
        migrations.AddField(
            model_name='cart',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_analysis', to='services.analysis', verbose_name='анализ'),
        ),
        migrations.AddField(
            model_name='cart',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_appointment', to='services.appointment', verbose_name='прием'),
        ),
        migrations.AddField(
            model_name='history',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_analysis', to='services.analysis', verbose_name='анализ'),
        ),
        migrations.AddField(
            model_name='history',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_appointment', to='services.appointment', verbose_name='прием'),
        ),
        migrations.AddField(
            model_name='history',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories_result', to='services.result', verbose_name='результат'),
        ),
    ]
