# Generated by Django 4.2.2 on 2024-12-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_appointment_options_and_more'),
        ('users', '0006_remove_cart_analyses_remove_cart_appointments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-payment_daytime',), 'verbose_name': 'история', 'verbose_name_plural': 'истории'},
        ),
        migrations.RemoveField(
            model_name='history',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='history',
            name='appointment',
        ),
        migrations.AddField(
            model_name='history',
            name='payment_daytime',
            field=models.DateTimeField(auto_now=True, verbose_name='дата и время оплаты'),
        ),
        migrations.AddField(
            model_name='history',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='history',
            name='service_info',
            field=models.TextField(blank=True, null=True, verbose_name='информация об услуге'),
        ),
        migrations.AlterField(
            model_name='history',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories_result', to='services.result', verbose_name='результат'),
        ),
    ]
