# Generated by Django 4.2.2 on 2025-01-04 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_history_options_remove_history_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('choose', 'Выберите специалиста'), ('therapist', 'Терапевт'), ('surgeon', 'Хирург'), ('ultrasound', 'УЗИ'), ('gastroenterologist', 'Гастроэнтеролог'), ('dermatologist', 'Дерматолог'), ('cardiologist', 'Кардиолог'), ('otorhinolaryngologist', 'Оториноларинголог'), ('neurologist', 'Невролог'), ('urologist', 'Уролог')], default='choose', max_length=30, verbose_name='специализация')),
                ('date', models.DateField(verbose_name='дата')),
                ('from_time', models.CharField(choices=[('08_00', '08:00'), ('08_30', '08:30'), ('09_00', '09:00'), ('09_30', '09:30'), ('10_00', '10:00'), ('10_30', '10:30'), ('11_00', '11:00'), ('11_30', '11:30'), ('12_00', '12:00'), ('12_30', '12:30'), ('13_00', '13:00'), ('13_30', '13:30'), ('14_00', '14:00'), ('14_30', '14:30'), ('15_00', '15:00'), ('15_30', '15:30'), ('16_00', '16:00'), ('16_30', '16:30'), ('17_00', '17:00'), ('17_30', '17:30'), ('18_00', '18:00'), ('18_30', '18:30'), ('19_00', '19:00'), ('19_30', '19:30')], default='08_00', max_length=5, verbose_name='с')),
                ('to_time', models.CharField(choices=[('08_30', '08:30'), ('09_00', '09:00'), ('09_30', '09:30'), ('10_00', '10:00'), ('10_30', '10:30'), ('11_00', '11:00'), ('11_30', '11:30'), ('12_00', '12:00'), ('12_30', '12:30'), ('13_00', '13:00'), ('13_30', '13:30'), ('14_00', '14:00'), ('14_30', '14:30'), ('15_00', '15:00'), ('15_30', '15:30'), ('16_00', '16:00'), ('16_30', '16:30'), ('17_00', '17:00'), ('17_30', '17:30'), ('18_00', '18:00'), ('18_30', '18:30'), ('19_00', '19:00'), ('19_30', '19:30'), ('20_00', '20:00')], default='20_00', max_length=5, verbose_name='до')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ф.И.О.')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки на запись на прием',
                'ordering': ('-date',),
            },
        ),
    ]
