# Generated by Django 4.2.2 on 2025-01-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_usersappointment'),
        ('users', '0008_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='appointment',
        ),
        migrations.AddField(
            model_name='cart',
            name='users_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_users_appointment', to='services.usersappointment', verbose_name='прием пользователя'),
        ),
    ]
