# Generated by Django 4.2.2 on 2025-01-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_cart_appointment_cart_users_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='specialization',
        ),
    ]
