# Generated by Django 4.2.2 on 2025-01-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_doctor_speciality'),
        ('users', '0010_remove_request_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_speciality', to='services.speciality', verbose_name='специализация'),
        ),
    ]
