# Generated by Django 4.2.2 on 2024-10-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('treatment_room', models.PositiveSmallIntegerField(verbose_name='процедурный кабинет')),
                ('price', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_doctor', to='services.doctor', verbose_name='врач')),
            ],
            options={
                'verbose_name': 'прием',
                'verbose_name_plural': 'приемы',
                'ordering': ('price',),
            },
        ),
    ]
