# Generated by Django 4.2.2 on 2024-10-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_doctor', to='services.doctor', verbose_name='врач'),
        ),
    ]
