# Generated by Django 4.2.2 on 2024-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_analysis_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_placeholder.jpg', null=True, upload_to='services/avatars', verbose_name='аватар'),
        ),
    ]
