# Generated by Django 4.2.2 on 2025-01-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время приема')),
                ('js_data', models.JSONField(verbose_name='json данные')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_appointments_doctor', to='services.doctor', verbose_name='врач')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_appointments_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'пользовательский прием',
                'verbose_name_plural': 'пользовательские приемы',
            },
        ),
    ]
