# Generated by Django 4.2.2 on 2025-01-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_usersappointment_js_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('doctor',), 'verbose_name': 'прием', 'verbose_name_plural': 'приемы'},
        ),
    ]
