# Generated by Django 4.2.2 on 2024-12-19 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Ф.И.О.')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('date_created', models.DateField(auto_now=True, verbose_name='время создания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='признак закрытости')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
    ]
