# Generated by Django 4.2.2 on 2024-12-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
